language: python
python:
- 3.9.12

install:
- pip install -r requirements.txt

before_script:
- source prepare-conda-env.sh

script:
- pytest tutorial_example_1.py
- pytest tutorial_example_2.py
- pytest tutorial_example_3.py
- pytest task_1.py
- pytest task_2.py
- pytest task_3.py
- pytest task_4.py